### PR TITLE
Fix send runes

### LINKED ISSUE #3620: A useless postage was added to the sending runes tx?
Query Balance:

PS D:\Projects\bitcoin\ord> ordtest wallet balance
` 
{
  "cardinal": 46553843,
  "ordinal": 20000,
  "runes": {
    "xxxxxxx": "1000000",
    "MEME•OF•RUNES": "24",
    "xxxxxxx": "381000000",
    "xxxxxxx": "20000"
  },
  "runic": 1450000,
  "total": 48023843
}
`

send runes: 
PS D:\Projects\bitcoin\ord> ordtest wallet send --fee-rate 100 tb1pt0v7eye37l38e50lnywfu6atj2ec6dzteduqa4xasqnn6ndckcuqx83fsn 24:MEME•OF•RUNES
`
{
  "txid": "07537f2643f790535e12a2211f78ec82e2cfef866b694ba6d653a2caecf592f9",
  "psbt": "xxxx",
  "outgoing": "24:MEME•OF•RUNES",
  "fee": 27600
}
`

The payload in OP_RETURN:
`
0099ee9d0110e01202
`

Dechiper result:
`
{"edicts":[{"id":{"block":"2586393","tx":"16"},"amount":"2400","output":"2"}]}
`

[Tx in mempool](https://mempool.space/zh/testnet/tx/07537f2643f790535e12a2211f78ec82e2cfef866b694ba6d653a2caecf592f9)

This transaction only requires one postage, why are there two postage outputs in the transaction?

### PR DESCRIPTION
**Pull request by raphjaph**
Fixes #3620

### CODE REVIEW

**Comment by raphjaph** [comment]
@casey This is ready for review

**Review by casey — APPROVED** [review]
LGTM

File: src/subcommand/wallet/send.rs [hunk 1]
```diff
@@ -209,17 +210,14 @@ impl Send {
     destination: Address,
     spaced_rune: SpacedRune,
     decimal: Decimal,
+    postage: Amount,
```
Comment (twosatsmaxi) [inline src/subcommand/wallet/send.rs:213]: comment ref.
